name: simple_text_field
description: Create minimal-looking, standarized TextFields with ease
version: 0.0.1
author: Nikolai Henriksen<henriksennikolai@hotmail.com>
homepage: https://github.com/nikolaihen/simple_text_field.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: